language: ruby

gemfile:
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - jruby-9.1.6.0

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/rails5_0.gemfile

notifications:
  email: false

bundler_args: --without development

services:
  - mongodb

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
